export type EditorialSection = 'today' | 'featured' | 'daily' | 'kids';

export interface EditorialArticle {
  id: string;
  titleZh: string;
  titleEn: string;
  summaryZh: string;
  keyPointsZh: readonly string[];
  source: string;
  category: string;
  wordCount: number;
  minutes: number;
  level: string;
  image: string;
  section: EditorialSection;
  publishedAt: string;
  paragraphs: readonly string[];
}

const image = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=900&q=70`;

export const editorialArticles = [
  {
    id: 'hero',
    titleZh: '考古学家在 2.5 万年前牙齿中发现习惯性用药证据',
    titleEn: 'World’s Oldest Evidence of Habitual Drug Use Found in Ancient Teeth',
    summaryZh: '苏拉威西洞穴出土的狩猎采集者牙齿带有特殊磨痕与生物碱残留，可能把人类习惯性药物使用的证据推到 1.6–2.5 万年前。',
    keyPointsZh: ['牙齿磨痕如何保存行为证据', '槟榔类植物与史前成瘾风险', '为什么“使用”不等于现代意义的滥用'],
    source: 'Smithsonian Magazine',
    category: '考古',
    wordCount: 1180,
    minutes: 8,
    level: '雅思 6.5',
    section: 'today',
    image: image('1484406566174-9da000fda645'),
    publishedAt: '2026-09-11',
    paragraphs: [
      'Researchers say marks and chemical traces on teeth from a Sulawesi cave may record repeated use of a stimulant plant by a hunter-gatherer who lived up to 25,000 years ago.',
      'The finding does not prove modern addiction, but it suggests that mind-altering plants were part of how some early people managed pain, hunger, or ritual life.',
    ],
  },
  {
    id: 'a1',
    titleZh: '鹰与狼：爱尔兰地名里留存下来的失落动物',
    titleEn: 'The Long-Lost Animals That Live On in Irish Place Names',
    summaryZh: '爱尔兰地名保存着已消失动物的回声，研究者把这些名称当作传统生态知识，用于理解洪水、栖息地丧失与再野化。',
    keyPointsZh: ['地名如何成为生态档案', '传统知识怎样补充现代数据', '再野化争议中的历史证据'],
    source: 'BBC Future',
    category: '自然',
    wordCount: 1320,
    minutes: 9,
    level: '雅思 6.5',
    section: 'featured',
    image: image('1518770660439-4636190af475'),
    publishedAt: '2026-09-10',
    paragraphs: [
      'Across Ireland, names for hills, rivers, and fields still carry the memory of eagles, wolves, and wild boar that vanished from the landscape centuries ago.',
      'Researchers are treating those names as evidence about where animals once lived, while asking whether linguistic memory can guide flood planning and rewilding debates today.',
    ],
  },
  {
    id: 'a2',
    titleZh: '世界领导人正在失去对核战争的恐惧',
    titleEn: 'World Leaders Are Losing Their Terror of Nuclear War',
    summaryZh: '文章讨论核威慑心态的变化：当恐惧被视为过时，误判风险可能上升。',
    keyPointsZh: ['恐惧为何也能维持稳定', '核风险叙事怎样变化', '威慑与误判之间的界线'],
    source: 'The Economist',
    category: '国际',
    wordCount: 1260,
    minutes: 8,
    level: '考研',
    section: 'featured',
    image: image('1441974231531-c6227db76b6e'),
    publishedAt: '2026-09-08',
    paragraphs: [
      'The piece argues that fear can paralyze societies, but fear of nuclear war has also restrained leaders who understood how quickly escalation could run out of control.',
      'When that terror fades, the danger is not confidence itself; it is the temptation to treat nuclear threats as ordinary tools of pressure.',
    ],
  },
  {
    id: 'a3',
    titleZh: '青少年正在变得更迟钝吗',
    titleEn: 'Are Teenagers Growing Dimmer?',
    summaryZh: '围绕青少年认知与学业表现趋势的讨论，核心问题是数据究竟显示了什么，以及学校、屏幕和家庭各自承担多少责任。',
    keyPointsZh: ['认知测试趋势如何解读', '屏幕时间与学校因素', '避免用单一指标判定一代人'],
    source: 'The Economist',
    category: '教育',
    wordCount: 1100,
    minutes: 7,
    level: '六级',
    section: 'featured',
    image: image('1521737604893-d14cc237f11d'),
    publishedAt: '2026-09-08',
    paragraphs: [
      'A worrying headline about teenagers hides a harder question: which skills are actually changing, and which tests merely reflect new habits of attention?',
      'Before declaring a generation dimmer, readers should separate curriculum effects, family stress, sleep loss, and the design of the measurements themselves.',
    ],
  },
  {
    id: 'a4',
    titleZh: '亲手弄脏双手，几周内可能改善健康',
    titleEn: 'Getting Your Hands Dirty Boosts Your Health Within Weeks',
    summaryZh: '芬兰研究提示，接触土壤、苔藓等富微生物环境，可能快速提升皮肤微生物多样性并影响免疫调节。',
    keyPointsZh: ['皮肤微生物组如何变化', '自然环境暴露的剂量问题', '卫生与多样性的平衡'],
    source: 'BBC Future',
    category: '健康',
    wordCount: 980,
    minutes: 6,
    level: '四级',
    section: 'featured',
    image: image('1543466835-00a7907e9de1'),
    publishedAt: '2026-09-04',
    paragraphs: [
      'In a Finnish experiment, people who handled soil, moss, and other microbe-rich materials showed changes in skin microbial diversity within weeks.',
      'The result does not mean dirt is medicine; it suggests that everyday contact with living environments may tune immune responses that modern indoor life rarely reaches.',
    ],
  },
  {
    id: 'a5',
    titleZh: '帮助受困宇航员回家的 300 岁工具',
    titleEn: 'The 300-Year-Old Tool Helping Stranded Astronauts Get Home',
    summaryZh: 'NASA 把六分仪等古典天文导航作为深空通信失联时的备份方案，国际空间站实验已验证手持测量的可行性。',
    keyPointsZh: ['六分仪如何测量角度', '为什么深空任务需要备份导航', '老技术与新系统如何互补'],
    source: 'BBC Future',
    category: '太空',
    wordCount: 1240,
    minutes: 8,
    level: '六级',
    section: 'featured',
    image: image('1521791136064-7986c2920216'),
    publishedAt: '2026-09-04',
    paragraphs: [
      'Long before satellite navigation, sailors fixed their position by measuring the angle between a star and the horizon with a sextant.',
      'Space agencies are revisiting that idea because a crew far from Earth could lose radio links and still need a way to estimate where they are.',
    ],
  },
  {
    id: 'a6',
    titleZh: '美国人愿意为长寿放弃什么',
    titleEn: 'What Americans Would Give Up for a Longer Life',
    summaryZh: '《国家地理》独家民调显示，64% 的受访者宁愿寿命较短但无病，也不愿带病长寿；只有 9% 认为衰老应被当作要主动治疗的医学问题。',
    keyPointsZh: ['寿命与健康寿命的区别', '公众如何理解抗衰老医学', '调查样本与表述的局限'],
    source: 'National Geographic',
    category: '健康',
    wordCount: 1040,
    minutes: 7,
    level: '四级',
    section: 'featured',
    image: image('1504711434969-e33886168f5c'),
    publishedAt: '2026-08-18',
    paragraphs: [
      'A survey commissioned with a longevity issue asked Americans to choose between more years and healthier years, and many favored health over sheer duration.',
      'Only a small minority described aging itself as a medical problem science should try to cure, even as biotech companies race to slow or reverse it.',
    ],
  },
  {
    id: 'a7',
    titleZh: '对付斑衣蜡蝉的意外秘密武器',
    titleEn: 'The Surprising Secret Weapon Against Spotted Lanternflies',
    summaryZh: '初步实验发现，取食马利筋的斑衣蜡蝉在 24 小时内死亡率明显上升，种植本土马利筋可能成为治理入侵害虫的新线索。',
    keyPointsZh: ['入侵物种如何扩散', '马利筋、帝王蝶与害虫治理', '初步结果为何不能过度外推'],
    source: 'National Geographic',
    category: '动物',
    wordCount: 920,
    minutes: 6,
    level: '四级',
    section: 'featured',
    image: image('1504674900247-0877df9cc836'),
    publishedAt: '2026-09-01',
    paragraphs: [
      'Spotted lanternflies have spread across much of the eastern United States, prompting searches for controls that do not simply spray more chemicals.',
      'Early tests suggest that insects feeding on milkweed can die within a day, a clue that native plantings might pressure the pest while also supporting monarch butterflies.',
    ],
  },
  {
    id: 'a8',
    titleZh: '实验性疫苗让严重过敏反应一年内不再发作',
    titleEn: 'Experimental Vaccine Prevents Dangerous Allergic Attack for a Year',
    summaryZh: '小鼠实验显示，通过阻断令免疫系统过度反应的分子，一款疫苗可把致命过敏性休克的防护维持一年。',
    keyPointsZh: ['过敏性休克的免疫机制', '疫苗式防护与急救药物差异', '动物结果到人体应用的距离'],
    source: 'New Scientist',
    category: '医学',
    wordCount: 860,
    minutes: 5,
    level: '六级',
    section: 'featured',
    image: image('1502602898657-3e91760cbb34'),
    publishedAt: '2025-12-03',
    paragraphs: [
      'An experimental vaccine protected mice from anaphylaxis for a year by blocking a molecule that helps drive the immune system into overreaction.',
      'The work is far from a human treatment, but it points toward prevention for people whose allergies can turn an ordinary exposure into an emergency.',
    ],
  },
  {
    id: 'n1',
    titleZh: '通胀在全球回归，抗通胀之战也随之回来',
    titleEn: 'Inflation Is Back Around the World—as Is the Fight Against It',
    summaryZh: '通胀压力在多个经济体重新抬头，各国央行被迫重新考虑加息与紧缩节奏。',
    keyPointsZh: ['通胀回归的共同驱动', '央行为何重新转鹰', '价格稳定与增长之间的取舍'],
    source: 'The Economist',
    category: '快讯',
    wordCount: 760,
    minutes: 4,
    level: '六级',
    section: 'daily',
    image: image('1457369804613-52c61a468e7d'),
    publishedAt: '2026-09-06',
    paragraphs: [
      'After a period in which inflation seemed to be retreating, price pressures are again forcing central banks to defend their credibility.',
      'The renewed fight is not only about interest rates; it is about convincing households and firms that temporary shocks will not become permanent expectations.',
    ],
  },
  {
    id: 'n2',
    titleZh: '就业末日被推迟了，AI 就业热潮正在到来',
    titleEn: 'The Jobs Apocalypse Is Postponed. An AI Jobs Boom Is Here',
    summaryZh: '文章测算 AI 迄今在美国净创造约 100 万个岗位，超过同期归因于 AI 的约 20 万个裁员，但客服与行政岗位承压。',
    keyPointsZh: ['AI 岗位创造来自哪里', '裁员与新增为何同时发生', '数据中心建设对劳动力市场的影响'],
    source: 'The Economist',
    category: '快讯',
    wordCount: 820,
    minutes: 5,
    level: '考研',
    section: 'daily',
    image: image('1518709268805-4e9042af9f23'),
    publishedAt: '2026-09-04',
    paragraphs: [
      'The predicted collapse of white-collar work has not arrived; instead, data-center construction, electrical work, and AI engineering have added jobs.',
      'That boom can coexist with real losses in customer support and administration, which is why aggregate numbers hide painful transitions.',
    ],
  },
  {
    id: 'n3',
    titleZh: '我在街区寻找监控摄像头，发现的比想象多得多',
    titleEn: 'I Found Far More Surveillance Cameras Than I Expected',
    summaryZh: '记者随监督组织在纽约街区清点摄像头，介绍警方平台、私人网络争议，以及公众可用的监控地图工具。',
    keyPointsZh: ['公共与私人监控如何叠加', 'Flock 与警方平台的争议', '居民怎样自查周边摄像头'],
    source: 'BBC Future',
    category: '快讯',
    wordCount: 790,
    minutes: 5,
    level: '六级',
    section: 'daily',
    image: image('1497366216548-37526070297c'),
    publishedAt: '2026-09-02',
    paragraphs: [
      'A walk through one neighborhood becomes uncomfortable when every doorbell, storefront, and pole is counted as a possible sensor.',
      'Civil-liberties groups argue that mapping surveillance is a first step toward asking who watches the footage and how long it is kept.',
    ],
  },
  {
    id: 'n4',
    titleZh: 'SpaceX 火箭部件撞上月球，仪器看到了什么',
    titleEn: 'What Instruments Saw When a SpaceX Rocket Part Hit the Moon',
    summaryZh: '猎鹰 9 号上面级按预测撞击月球后，韩国 Danuri 轨道器拍下撞击前后对比，甚大望远镜在尘埃羽流中检测到钠和锂信号。',
    keyPointsZh: ['月球撞击如何被确认', '尘埃羽流中的化学指纹', '太空垃圾责任问题'],
    source: 'Smithsonian Magazine',
    category: '快讯',
    wordCount: 840,
    minutes: 5,
    level: '六级',
    section: 'daily',
    image: image('1446776811953-b23d57bd42aa'),
    publishedAt: '2026-08-07',
    paragraphs: [
      'A spent Falcon 9 upper stage struck the Moon as predicted, and orbiters compared before-and-after images to locate the new crater.',
      'Telescopes looking at the dust plume reported chemical fingerprints such as sodium and lithium, renewing questions about who owns the debris humans leave on other worlds.',
    ],
  },
  {
    id: 'n5',
    titleZh: '计划中的卫星发射可能毁掉哈勃图像',
    titleEn: 'Planned Satellite Launches Could Ruin Hubble Space Telescope Images',
    summaryZh: '模拟显示，到 2030 年代末计划发射的卫星超过 50 万颗，可能显著影响哈勃等天基望远镜的观测质量。',
    keyPointsZh: ['卫星轨迹如何进入图像', '天文观测的时间窗口', '商业星座与公共科学的冲突'],
    source: 'New Scientist',
    category: '快讯',
    wordCount: 730,
    minutes: 4,
    level: '六级',
    section: 'daily',
    image: image('1451187580459-43490279c0fa'),
    publishedAt: '2025-12-03',
    paragraphs: [
      'Simulations of planned constellations suggest that hundreds of thousands of satellites could cross the fields of space telescopes.',
      'The problem is not a single ruined photograph; it is the loss of clean observing time that cannot be recovered once a streak passes through.',
    ],
  },
  {
    id: 'n6',
    titleZh: '月球形成可能需要早期地球遭遇三次大撞击',
    titleEn: 'Forming Moon May Have Taken Three Big Impacts Early in Earth’s History',
    summaryZh: '新模型挑战“一次大撞击形成月球”的传统图景，认为多次撞击序列或许更符合地球与月球的化学相似性。',
    keyPointsZh: ['大碰撞假说的证据', '三次撞击模型想解释什么', '同位素相似性为何关键'],
    source: 'New Scientist',
    category: '快讯',
    wordCount: 710,
    minutes: 4,
    level: '六级',
    section: 'daily',
    image: image('1447433589675-4aaa566f3f05'),
    publishedAt: '2025-12-03',
    paragraphs: [
      'The classic story says one giant impact blasted material into orbit that became the Moon.',
      'A three-impact alternative tries to explain why Earth and the Moon are chemically similar without requiring one perfectly tuned collision.',
    ],
  },
  {
    id: 'n7',
    titleZh: '批诺兰电影“糟糕”后，《奥德赛》译者 Emily Wilson 从零重译',
    titleEn: 'Emily Wilson Starts Over on the Odyssey After Calling Nolan Film “Abysmal”',
    summaryZh: '首位完整英译《奥德赛》的女性译者宣布将重新翻译这部史诗，风格更接近她的《伊利亚特》译本，工程约已完成一半。',
    keyPointsZh: ['重译为何不是小修小补', '史诗翻译中的节奏与称谓', '影视改编与文本距离'],
    source: 'Smithsonian Magazine',
    category: '文化',
    wordCount: 690,
    minutes: 4,
    level: '雅思 6.5',
    section: 'daily',
    image: image('1481627834876-b7833e8f5570'),
    publishedAt: '2026-08-31',
    paragraphs: [
      'Emily Wilson, whose Odyssey translation was widely praised, says she is retranslating the poem rather than revising a few famous lines.',
      'The decision follows her harsh criticism of a blockbuster adaptation, but the deeper issue is how a translator keeps Homer strange, swift, and morally unsettling in English.',
    ],
  },
  {
    id: 'k1',
    titleZh: '这只孤儿小象如何逆转发运',
    titleEn: 'How This Orphaned Elephant Defied the Odds',
    summaryZh: '尼日利亚 Okomu 国家公园救助了该国第一只存活的孤儿非洲森林象幼崽；当地森林象仅存约 400 只，长期目标是断奶后放归野外。',
    keyPointsZh: ['孤儿象救助为何困难', '森林象与草原象的区别', '放归野外前要满足什么条件'],
    source: 'National Geographic',
    category: '少儿',
    wordCount: 560,
    minutes: 3,
    level: '中考',
    section: 'kids',
    image: image('1557050543-4d5f4e07ef46'),
    publishedAt: '2026-09-03',
    paragraphs: [
      'Rangers in Nigeria are caring for an orphaned forest elephant calf whose name means “survivor” in the Ijaw language.',
      'The long-term hope is to return him to the wild after weaning, but that depends on health, habitat safety, and whether he can learn to live with other elephants.',
    ],
  },
  {
    id: 'k2',
    titleZh: '看百万条鲻鱼在大西洋里成群移动',
    titleEn: 'Witness Millions of Mullet Swarming in the Atlantic',
    summaryZh: '每年秋冬，大量条纹鲻鱼沿佛罗里达海岸迁徙；禁用缠绕网具后种群恢复，使这场迁徙成为北美壮观的海洋鱼类移动之一。',
    keyPointsZh: ['鲻鱼为什么成群迁徙', '渔具禁令如何帮助恢复', '观看野生动物时要保持距离'],
    source: 'National Geographic',
    category: '少儿',
    wordCount: 540,
    minutes: 3,
    level: '中考',
    section: 'kids',
    image: image('1535591273668-578e31182c4f'),
    publishedAt: '2026-09-09',
    paragraphs: [
      'Each autumn and winter, striped mullet gather in enormous schools that can stretch along the Florida coast.',
      'The spectacle follows a recovery after Florida banned certain entangling nets decades ago, showing how one rule can change what people later see in the water.',
    ],
  },
  {
    id: 'k3',
    titleZh: '这颗小行星其实是两块粘在一起的太空岩石',
    titleEn: 'This Asteroid Is Actually Two Conjoined Space Rocks',
    summaryZh: '隼鸟 2 号飞掠小行星 Torifune 时拍到特写：它像花生一样由两块岩石相接，属于“相接双星”，数据将帮助行星防御研究。',
    keyPointsZh: ['相接双星是什么', '近距离拍照能测到什么', '小行星形状为何影响防御'],
    source: 'Smithsonian Magazine',
    category: '少儿',
    wordCount: 520,
    minutes: 3,
    level: '中考',
    section: 'kids',
    image: image('1462331940025-496dfbfc7564'),
    publishedAt: '2026-07-08',
    paragraphs: [
      'New close-up images show that asteroid Torifune is shaped like a peanut because two rocks are stuck together.',
      'Scientists call this a contact binary, and knowing the shape helps them model how such objects spin, break apart, or might be nudged away from Earth.',
    ],
  },
  {
    id: 'k4',
    titleZh: '养狗可能通过微生物组让我们更友善',
    titleEn: 'Dogs May Make Us More Caring by Changing Our Microbiome',
    summaryZh: '新研究提示，养狗似乎会以可能提升幸福感的方式改变人体微生物生态，但因果关系仍需更多证据。',
    keyPointsZh: ['微生物组是什么', '宠物如何改变家庭环境', '相关性与因果性的差别'],
    source: 'New Scientist',
    category: '少儿',
    wordCount: 510,
    minutes: 3,
    level: '中考',
    section: 'kids',
    image: image('1583511655857-d19b40a7a54e'),
    publishedAt: '2025-12-03',
    paragraphs: [
      'Pets bring microbes into a home on fur, paws, and saliva, and dogs may change the human microbiome in ways linked with sociability.',
      'The study is intriguing, but it cannot yet prove that dogs alone make people kinder; families who choose dogs may already differ in many ways.',
    ],
  },
] as const satisfies readonly EditorialArticle[];

export function getEditorialArticle(id: string): EditorialArticle | undefined {
  return editorialArticles.find((article) => article.id === id);
}

export function getEditorialSection(section: EditorialSection): EditorialArticle[] {
  return editorialArticles.filter((article) => article.section === section);
}

export function searchEditorialArticles(query: string): EditorialArticle[] {
  const normalized = query.trim().toLocaleLowerCase();
  if (!normalized) return [...editorialArticles];
  return editorialArticles.filter((article) =>
    [article.titleZh, article.titleEn, article.source, article.category].some(
      (value) => value.toLocaleLowerCase().includes(normalized),
    ),
  );
}
