export const errorCodes = [
  'VALIDATION_ERROR',
  'AGE_CONFIRMATION_REQUIRED',
  'UNAUTHORIZED',
  'TOKEN_REVOKED',
  'EMAIL_AUTH_FAILED',
  'PASSWORD_RESET_UNAVAILABLE',
  'PASSWORD_RESET_CODE_INVALID',
  'WECHAT_NOT_CONFIGURED',
  'WECHAT_AUTH_FAILED',
  'AUTH_ACCOUNT_CONFLICT',
  'NOT_FOUND',
  'STATE_CONFLICT',
  'IDEMPOTENCY_KEY_REUSED',
  'INSUFFICIENT_VOCABULARY',
  'VOCABULARY_CHANGED',
  'FREE_LIMIT_REACHED',
  'RATE_LIMITED',
  'AI_UNAVAILABLE',
  'AI_INVALID_OUTPUT',
  'AI_CONTENT_REJECTED',
  'GENERATION_DEADLINE_EXCEEDED',
  'IMPORT_UNSUPPORTED_TYPE',
  'IMPORT_TOO_LARGE',
  'IMPORT_CONTENT_INVALID',
  'IMPORT_NOT_ENGLISH',
  'IMPORT_FETCH_BLOCKED',
  'IMPORT_FETCH_FAILED',
  'IMPORT_PARSE_FAILED',
  'IMPORT_SOURCE_REQUIRES_ACCESS',
  'IMPORT_OCR_FAILED',
  'IMPORT_DEADLINE_EXCEEDED',
  'UPLOAD_SESSION_EXPIRED',
  'UPLOAD_SESSION_USED',
  'SIMILAR_ARTICLE_REQUIRES_DECISION',
  'DATABASE_UNAVAILABLE',
  'INTERNAL_ERROR',
] as const;

export type ErrorCode = (typeof errorCodes)[number];

export class AppError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message: string,
    public readonly statusCode: number,
    public readonly retryable = false,
  ) {
    super(message);
    this.name = 'AppError';
  }
}
