import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useState } from 'react';
import { Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useLayoutWidth } from '@/components/useLayoutWidth';
import { fonts } from '@/constants/theme';
import { useAppTheme } from '@/context/ThemeContext';
import { useLearningMode, type LearningMode } from '@/context/LearningModeContext';
import { getVipPlans, readingBenefits, speakingBenefits, type VipBenefit } from './plans';

export function SubscriptionScreen() {
  const { theme } = useAppTheme();
  const { mode } = useLearningMode();
  const insets = useSafeAreaInsets();
  const wide = useLayoutWidth() >= 900;
  const [planIndex, setPlan] = useState(0);
  const [benefitChoice, setBenefitMode] = useState<LearningMode | null>(null);
  const benefitMode = benefitChoice ?? mode;
  const [sheet, setSheet] = useState<'invite' | 'info' | null>(null);
  const pricingChannel = Platform.OS === 'ios' ? 'apple' : 'web';
  const vipPlans = getVipPlans(pricingChannel);
  const pricingLabel = pricingChannel === 'apple' ? 'App Store 价格' : Platform.OS === 'web' ? '网页端价格' : '会员价格';
  const plan = vipPlans[planIndex];
  const back = () => router.canGoBack() ? router.back() : router.replace('/(tabs)/profile');
  const rows = (items: VipBenefit[]) => <View style={wide ? styles.grid : undefined}>{items.map(item => <View key={item.title} style={[styles.benefit, { borderBottomColor: theme.border }, wide && styles.gridItem]}><Ionicons name={item.icon} size={22} color={theme.accent} /><View style={{ flex: 1 }}><Text style={{ color: theme.text, fontSize: 15, lineHeight: 23 }}>{item.title}</Text><Text style={[styles.hint, { color: theme.textMuted }]}>{item.description}</Text></View></View>)}</View>;
  return <View style={[styles.page, { backgroundColor: theme.bg }]}>
    <View style={[styles.header, { paddingTop: insets.top + 4 }]}><Pressable accessibilityRole="button" accessibilityLabel="返回" onPress={back} style={styles.touch}><Ionicons name="arrow-back" size={24} color={theme.text} /></Pressable><Text accessibilityRole="header" style={{ color: theme.text, fontSize: 16 }}>开通 VIP</Text><Pressable accessibilityRole="button" accessibilityLabel="兑换邀请码" onPress={() => setSheet('invite')} style={styles.touch}><Text style={{ color: theme.accent }}>兑换</Text></Pressable></View>
    <ScrollView stickyHeaderIndices={[2]} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
      <View style={[styles.top, wide && styles.topWide]}>
        <View style={[styles.hero, { backgroundColor: theme.vip }, wide && styles.heroWide]}><Text style={{ color: theme.onVip, fontSize: 10, letterSpacing: 2 }}>READ &amp; SPEAK</Text><View style={styles.heroRow}><View style={{ flex: 1 }}><Text style={[styles.heroTitle, { color: theme.onVip }]}>读得懂，</Text><Text style={[styles.heroTitle, { color: theme.pink }]}>也说得出。</Text></View><Text style={[styles.vip, { color: theme.pink }]}>VIP</Text></View><Text style={[styles.hint, { color: theme.onVip, marginTop: 16 }]}>一份 VIP，阅读与口语一起进步。</Text></View>
        <View style={[styles.planSection, wide && { flex: 1 }]}><Text style={[styles.sectionTitle, { color: theme.text }]}>选择你的 VIP</Text><Text style={[styles.hint, { color: theme.textMuted, marginBottom: 16 }]}>{pricingLabel} · 阅读与口语同享</Text><View style={styles.plans}>{vipPlans.map((item, index) => <Pressable key={item.id} accessibilityRole="button" accessibilityLabel={item.name} accessibilityState={{ selected: index === planIndex }} onPress={() => setPlan(index)} style={[styles.plan, { backgroundColor: planIndex === index ? theme.accentSoft : theme.surface, borderColor: planIndex === index ? theme.accent : theme.border }]}><Text style={{ fontSize: 12, color: theme.text }}>{item.name}</Text><View style={{ flexDirection: 'row', alignItems: 'baseline', marginTop: 8 }}><Text style={{ color: theme.accent, fontSize: 12 }}>¥</Text><Text style={[styles.price, { color: index === planIndex ? theme.accent : theme.text }]}>{item.price}</Text></View><Text style={[styles.hint, { color: theme.textMuted, textDecorationLine: 'line-through' }]}>¥{item.original}</Text><View style={{ flexDirection: 'row', alignItems: 'center', marginTop: 8, justifyContent: 'space-between', gap: 4 }}><Text style={{ color: theme.textMuted, fontSize: 10 }}>{item.days ? `${item.days} 天` : '长期有效'}</Text><Ionicons name={index === planIndex ? 'checkmark-circle' : 'ellipse-outline'} color={index === planIndex ? theme.accent : theme.border} size={16} /></View></Pressable>)}</View><Text testID="vip-plan-summary" style={[styles.hint, { color: theme.textMuted, textAlign: 'center', marginTop: 12 }]}>{plan.days ? `共 ${plan.days} 天 · 约 ${(plan.price / plan.days).toFixed(2)} 元 / 天` : '一次开通 · 长期有效'}</Text></View>
      </View>
      <View style={[styles.benefitHeading, { borderTopColor: theme.border }]}><Text style={[styles.sectionTitle, { color: theme.text }]}>VIP 专属权益</Text><Text style={{ color: theme.accent, fontSize: 11 }}>阅读＋口语同享</Text></View>
      <View accessibilityRole="tablist" style={[styles.tabs, { backgroundColor: theme.bg, borderColor: theme.border }]}>{(['read', 'speak'] as LearningMode[]).map(value => <Pressable key={value} accessibilityRole="tab" accessibilityState={{ selected: benefitMode === value }} aria-selected={benefitMode === value} accessibilityLabel={value === 'read' ? '阅读权益 4' : '口语权益 11'} onPress={() => setBenefitMode(value)} style={[styles.tab, { backgroundColor: benefitMode === value ? theme.pink : theme.bg }]}><Ionicons name={value === 'read' ? 'book-outline' : 'mic-outline'} color={benefitMode === value ? theme.onPink : theme.textMuted} size={19} /><Text style={{ color: benefitMode === value ? theme.onPink : theme.textMuted, fontSize: 12 }}>{value === 'read' ? '阅读权益' : '口语权益'}</Text><Text style={{ color: benefitMode === value ? theme.onPink : theme.textMuted, fontFamily: fonts.display, fontSize: 23 }}>{value === 'read' ? '4' : '11'}</Text></Pressable>)}</View>
      <View>{benefitMode === 'read' ? <>{rows(readingBenefits)}<Text style={[styles.hint, { color: theme.textMuted, marginTop: 12 }]}>具体使用次数与额度以正式上线说明为准。</Text></> : <><Text style={[styles.hint, { color: theme.textMuted, marginVertical: 12 }]}>从理解原句，到自然开口。</Text>{rows(speakingBenefits.filter(item => !item.group))}<View style={styles.extensionHeading}><Text style={{ color: theme.text, fontSize: 14 }}>更多学习场景</Text><Text style={[styles.badge, { color: theme.textMuted, borderColor: theme.border }]}>规划中</Text></View>{rows(speakingBenefits.filter(item => item.group))}<Text style={[styles.hint, { color: theme.textMuted, marginTop: 12 }]}>这 4 项拓展权益将在功能上线后开放。</Text></>}</View>
      <View style={{ marginTop: 30 }}><Text style={[styles.hint, { color: theme.textSecondary }]}>VIP 暂未开放购买 · 当前不会扣费。以上为拟定方案，正式价格、权益与使用额度以上线说明为准。AI 台词讲解服务正在准备中。</Text><Pressable accessibilityRole="button" onPress={() => router.push('/feature-guide')} style={styles.guide}><Text style={{ color: theme.accent }}>查看当前功能与使用方法</Text><Ionicons name="arrow-forward" color={theme.accent} size={18} /></Pressable></View>
    </ScrollView>
    <View style={[styles.footer, { borderTopColor: theme.border, backgroundColor: theme.bg, paddingBottom: Math.max(12, insets.bottom) }]}><View style={styles.footerInner}><Pressable disabled accessibilityRole="button" accessibilityState={{ disabled: true }} style={[styles.primary, { backgroundColor: theme.surfaceAlt }]}><Text style={{ color: theme.textMuted, fontSize: 15 }}>暂未开放开通</Text><Text style={{ color: theme.textMuted, fontFamily: fonts.display, fontSize: 30 }}>¥{plan.price}</Text></Pressable><View style={styles.footerMeta}><Text style={[styles.hint, { color: theme.textMuted }]}>拟定方案 · 不自动续费</Text><Pressable accessibilityRole="button" onPress={() => setSheet('info')} style={styles.touch}><Text style={{ color: theme.accent, fontSize: 11 }}>订阅说明</Text></Pressable></View><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><Pressable accessibilityRole="button" onPress={() => setSheet('invite')} style={styles.touch}><Text style={{ color: theme.accent, fontSize: 12 }}>邀请码兑换</Text></Pressable><Pressable accessibilityRole="button" onPress={back} style={styles.touch}><Text style={{ color: theme.accent, fontSize: 12 }}>继续学习</Text></Pressable></View></View></View>
    <Modal visible={sheet !== null} transparent animationType="fade" onRequestClose={() => setSheet(null)}><Pressable accessibilityLabel="关闭弹层" onPress={() => setSheet(null)} style={styles.backdrop}><Pressable onPress={event => event.stopPropagation()} style={[styles.sheet, { backgroundColor: theme.bg }]}><View style={styles.sheetHeading}><Text accessibilityRole="header" style={{ color: theme.text, fontSize: 22 }}>{sheet === 'invite' ? '邀请码兑换' : '订阅说明'}</Text><Pressable accessibilityRole="button" accessibilityLabel="关闭" onPress={() => setSheet(null)} style={styles.touch}><Ionicons name="close" color={theme.text} size={24} /></Pressable></View>{sheet === 'invite' ? <><Text style={[styles.hint, { color: theme.textMuted, marginBottom: 18 }]}>兑换服务上线后，可以兑换阅读与口语权益。</Text><TextInput accessibilityLabel="邀请码" editable={false} placeholder="兑换服务尚未开放" placeholderTextColor={theme.textMuted} style={[styles.input, { borderColor: theme.border, color: theme.text }]} /><Text style={[styles.hint, { color: theme.textMuted, marginTop: 16 }]}>当前不会验证或保存邀请码，也不会模拟兑换成功。</Text></> : <><Text style={[styles.hint, { color: theme.textSecondary }]}>阅读与口语共用一份 VIP。{plan.name}拟定价格 ¥{plan.price}，{plan.days ? `有效期 ${plan.days} 天` : '长期有效'}；当前未开放购买。</Text><Text style={[styles.hint, { color: theme.textSecondary, marginTop: 14 }]}>{pricingLabel}，正式购买金额以支付页面展示为准。当前方案不自动续费。规划中的权益将在相应功能上线后开放，具体权益与额度以正式说明为准。</Text></>}</Pressable></Pressable></Modal>
  </View>;
}
const styles = StyleSheet.create({
  page: { flex: 1 }, header: { paddingHorizontal: 14, paddingBottom: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, touch: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  content: { width: '100%', maxWidth: 1040, alignSelf: 'center', paddingHorizontal: 24, paddingTop: 20, paddingBottom: 32 }, top: { gap: 26 }, topWide: { flexDirection: 'row', alignItems: 'stretch', gap: 32 },
  hero: { borderRadius: 3, padding: 24 }, heroWide: { flex: 1, justifyContent: 'center' }, heroRow: { flexDirection: 'row', alignItems: 'center', marginTop: 12, gap: 10 }, heroTitle: { fontSize: 28, lineHeight: 37 }, vip: { fontFamily: fonts.display, fontSize: 88, lineHeight: 96 },
  planSection: { gap: 0 }, sectionTitle: { fontSize: 17, lineHeight: 26 }, hint: { fontSize: 11, lineHeight: 19, marginTop: 4 }, plans: { flexDirection: 'row', gap: 8 }, plan: { flex: 1, minWidth: 0, padding: 10, borderWidth: 1, borderRadius: 3 }, price: { fontFamily: fonts.display, fontSize: 39, lineHeight: 46 },
  benefitHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderTopWidth: .5, marginTop: 32, paddingTop: 22, marginBottom: 14 }, tabs: { flexDirection: 'row', padding: 3, gap: 3, borderWidth: .5, borderRadius: 3 }, tab: { flex: 1, minHeight: 46, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  benefit: { flexDirection: 'row', gap: 15, paddingVertical: 19, borderBottomWidth: .5, alignItems: 'flex-start' }, grid: { flexDirection: 'row', flexWrap: 'wrap', columnGap: 30 }, gridItem: { width: '48%' }, extensionHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 30 }, badge: { borderWidth: .5, fontSize: 10, padding: 5 },
  guide: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 48, marginTop: 12 }, footer: { borderTopWidth: .5, paddingTop: 12, paddingHorizontal: 24 }, footerInner: { width: '100%', maxWidth: 992, alignSelf: 'center' }, primary: { minHeight: 52, borderRadius: 3, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18 }, footerMeta: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  backdrop: { flex: 1, backgroundColor: '#00000066', padding: 24, justifyContent: 'center', alignItems: 'center' }, sheet: { width: '100%', maxWidth: 480, padding: 22, borderRadius: 4 }, sheetHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }, input: { borderWidth: 1, borderRadius: 3, minHeight: 48, paddingHorizontal: 14 },
});
