import React from 'react';
import { Modal, Pressable, ScrollView, Text, View } from 'react-native';
import { useAppTheme } from '@/context/ThemeContext';
import { speakingStyles } from './SpeakingComponents';

type Props = { visible: boolean; close: () => void; rate: number; changeRate: (rate: number) => void; repeatCount: number; setRepeatCount: (count: number) => void; gap: number; setGap: (gap: number) => void; fontSize: number; setFontSize: (size: number) => void; skipGaps: boolean; setSkipGaps: (skip: boolean) => void };
export function ShadowingSettings(props: Props) {
  const { theme } = useAppTheme();
  const choices = (label: string, values: number[], value: number, select: (value: number) => void, suffix = '') => <View><Text style={{ color: theme.text, fontSize: 15, marginTop: 18 }}>{label}</Text><View style={speakingStyles.chips}>{values.map(item => <Pressable key={item} accessibilityRole="button" accessibilityLabel={`${label} ${item === 0 && label === '复读次数' ? '不限' : item}${suffix}`} accessibilityState={{ selected: item === value }} onPress={() => select(item)} style={[speakingStyles.chip, { borderColor: theme.border, backgroundColor: item === value ? theme.accentSoft : theme.bg }]}><Text style={{ color: item === value ? theme.accent : theme.text }}>{item === 0 && label === '复读次数' ? '不限' : `${item}${suffix}`}</Text></Pressable>)}</View></View>;
  return <Modal visible={props.visible} transparent animationType="fade" onRequestClose={props.close}><Pressable onPress={props.close} accessibilityLabel="关闭练习设置" style={{ flex: 1, backgroundColor: '#00000066', justifyContent: 'center', alignItems: 'center', padding: 20 }}><Pressable onPress={event => event.stopPropagation()} style={{ backgroundColor: theme.bg, padding: 22, borderRadius: 4, width: '100%', maxWidth: 480, maxHeight: '85%' }}><ScrollView><Text accessibilityRole="header" style={{ color: theme.text, fontSize: 24 }}>练习设置</Text>
    {choices('播放速度', [.5, .75, 1, 1.25, 1.5, 1.75, 2], props.rate, props.changeRate, '×')}
    <View style={{ flexDirection: 'row', gap: 12, alignItems: 'center' }}><Pressable accessibilityRole="button" accessibilityLabel="减慢 0.05 倍" onPress={() => props.changeRate(Math.max(.5, Math.round((props.rate - .05) * 100) / 100))} style={speakingStyles.chip}><Text style={{ color: theme.accent }}>−</Text></Pressable><Text style={{ color: theme.text }}>{props.rate.toFixed(2)}×</Text><Pressable accessibilityRole="button" accessibilityLabel="加快 0.05 倍" onPress={() => props.changeRate(Math.min(2, Math.round((props.rate + .05) * 100) / 100))} style={speakingStyles.chip}><Text style={{ color: theme.accent }}>＋</Text></Pressable></View>
    {choices('复读次数', [1, 3, 5, 0], props.repeatCount, props.setRepeatCount)}{choices('复读停顿', [0, 1, 2], props.gap, props.setGap, '秒')}{choices('字幕字号', [17, 21, 25], props.fontSize, props.setFontSize)}
    <Pressable accessibilityRole="switch" accessibilityState={{ checked: props.skipGaps }} onPress={() => props.setSkipGaps(!props.skipGaps)} style={{ minHeight: 50, justifyContent: 'center' }}><Text style={{ color: theme.accent }}>跳过空白：{props.skipGaps ? '已开启' : '已关闭'}</Text></Pressable><Pressable accessibilityRole="button" onPress={props.close} style={{ minHeight: 50, justifyContent: 'center' }}><Text style={{ color: theme.accent }}>完成</Text></Pressable>
  </ScrollView></Pressable></Pressable></Modal>;
}
